declare module '*.png';
declare module '*.ico';
declare module '*.svg';
declare module '*.json';
declare module '*.wav';
declare module 'oddslib';
// not used
declare module 'odds-converter';
declare module "@alehuo/react-playing-cards";
