export const teamCodes: { [country: string]: string } = {
	'England': 'ENG',
	'Northern Ireland': 'NIR',
	'Scotland': 'SCT',
	'Wales': 'WLS',
	'Afghanistan': 'AFG',
	'Albania': 'ALB',
	'Algeria': 'DZA',
	'American Samoa': 'ASM',
	'Andorra': 'AND',
	'Angola': 'AGO',
	'Anguilla': 'AIA',
	'Antarctica': 'ATA',
	'Antigua and Barbuda': 'ATG',
	'Argentina': 'ARG',
	'Armenia': 'ARM',
	'Aruba': 'ABW',
	'Australia': 'AUS',
	'Austria': 'AUT',
	'Azerbaijan': 'AZE',
	'Bahamas': 'BHS',
	'Bahrain': 'BHR',
	'Bangladesh': 'BGD',
	'Barbados': 'BRB',
	'Belarus': 'BLR',
	'Belgium': 'BEL',
	'Belize': 'BLZ',
	'Benin': 'BEN',
	'Bermuda': 'BMU',
	'Bhutan': 'BTN',
	'Bolivia': 'BOL',
	'Bosnia and Herzegovina': 'BIH',
	'Botswana': 'BWA',
	'Bouvet Island': 'BVT',
	'Brazil': 'BRA',
	'British Virgin Islands': 'VGB',
	'Brunei Darussalam': 'BRN',
	'Bulgaria': 'BGR',
	'Burkina Faso': 'BFA',
	'Burundi': 'BDI',
	'Cambodia': 'KHM',
	'Cameroon': 'CMR',
	'Canada': 'CAN',
	'Cape Verde': 'CPV',
	'Cayman Islands': 'CYM',
	'Central African Republic': 'CAF',
	'Chad': 'TCD',
	'Chile': 'CHL',
	'China': 'CHN',
	'Colombia': 'COL',
	'Comoros': 'COM',
	'Cook Islands': 'COK',
	'Costa Rica': 'CRI',
	'Croatia': 'HRV',
	'Cuba': 'CUB',
	'Cyprus': 'CYP',
	'Czech Republic': 'CZE',
	'Denmark': 'DNK',
	'Djibouti': 'DJI',
	'Dominica': 'DMA',
	'Dominican Republic': 'DOM',
	'Ecuador': 'ECU',
	'Egypt': 'EGY',
	'El Salvador': 'SLV',
	'Equatorial Guinea': 'GNQ',
	'Eritrea': 'ERI',
	'Estonia': 'EST',
	'Ethiopia': 'ETH',
	'Falkland Islands': 'FLK',
	'Faroe Islands': 'FRO',
	'Fiji': 'FJI',
	'Finland': 'FIN',
	'France': 'FRA',
	'French Guiana': 'GUF',
	'French Polynesia': 'PYF',
	'Gabon': 'GAB',
	'Gambia': 'GMB',
	'Georgia': 'GEO',
	'Germany': 'DEU',
	'Ghana': 'GHA',
	'Gibraltar': 'GIB',
	'Greece': 'GRC',
	'Greenland': 'GRL',
	'Grenada': 'GRD',
	'Guadeloupe': 'GLP',
	'Guam': 'GUM',
	'Guatemala': 'GTM',
	'Guernsey': 'GGY',
	'Guinea': 'GIN',
	'Guinea-Bissau': 'GNB',
	'Guyana': 'GUY',
	'Haiti': 'HTI',
	'Heard and Mcdonald Islands': 'HMD',
	'Honduras': 'HND',
	'Hungary': 'HUN',
	'Iceland': 'ISL',
	'India': 'IND',
	'Indonesia': 'IDN',
	'Iran': 'IRN',
	'Iraq': 'IRQ',
	'Ireland': 'IRL',
	'Isle of Man': 'IMN',
	'Israel': 'ISR',
	'Italy': 'ITA',
	'Jamaica': 'JAM',
	'Japan': 'JPN',
	'Jersey': 'JEY',
	'Jordan': 'JOR',
	'Kazakhstan': 'KAZ',
	'Kenya': 'KEN',
	'Kiribati': 'KIR',
	'North Korea': 'PRK',
	'South Korea': 'KOR',
	'Kuwait': 'KWT',
	'Kyrgyzstan': 'KGZ',
	'Lao': 'LAO',
	'Latvia': 'LVA',
	'Lebanon': 'LBN',
	'Lesotho': 'LSO',
	'Liberia': 'LBR',
	'Libya': 'LBY',
	'Liechtenstein': 'LIE',
	'Lithuania': 'LTU',
	'Luxembourg': 'LUX',
	'Macedonia': 'MKD',
	'Madagascar': 'MDG',
	'Malawi': 'MWI',
	'Malaysia': 'MYS',
	'Maldives': 'MDV',
	'Mali': 'MLI',
	'Malta': 'MLT',
	'Marshall Islands': 'MHL',
	'Martinique': 'MTQ',
	'Mauritania': 'MRT',
	'Mauritius': 'MUS',
	'Mayotte': 'MYT',
	'Mexico': 'MEX',
	'Moldova': 'MDA',
	'Monaco': 'MCO',
	'Mongolia': 'MNG',
	'Montenegro': 'MNE',
	'Montserrat': 'MSR',
	'Morocco': 'MAR',
	'Mozambique': 'MOZ',
	'Myanmar': 'MMR',
	'Namibia': 'NAM',
	'Nauru': 'NRU',
	'Nepal': 'NPL',
	'Netherlands': 'NLD',
	'Netherlands Antilles': 'ANT',
	'New Caledonia': 'NCL',
	'New Zealand': 'NZL',
	'Nicaragua': 'NIC',
	'Niger': 'NER',
	'Nigeria': 'NGA',
	'Niue': 'NIU',
	'Norfolk Island': 'NFK',
	'Northern Mariana Islands': 'MNP',
	'Norway': 'NOR',
	'Oman': 'OMN',
	'Pakistan': 'PAK',
	'Palau': 'PLW',
	'Palestinian Territory': 'PSE',
	'Panama': 'PAN',
	'Papua New Guinea': 'PNG',
	'Paraguay': 'PRY',
	'Peru': 'PER',
	'Philippines': 'PHL',
	'Pitcairn': 'PCN',
	'Poland': 'POL',
	'Portugal': 'PRT',
	'Puerto Rico': 'PRI',
	'Qatar': 'QAT',
	'Réunion': 'REU',
	'Romania': 'ROU',
	'Russian Federation': 'RUS',
	'Rwanda': 'RWA',
	'Saint-Barthélemy': 'BLM',
	'Saint Helena': 'SHN',
	'Saint Kitts and Nevis': 'KNA',
	'Saint Lucia': 'LCA',
	'Saint-Martin': 'MAF',
	'Saint Pierre and Miquelon': 'SPM',
	'Saint Vincent and Grenadines': 'VCT',
	'Samoa': 'WSM',
	'San Marino': 'SMR',
	'Sao Tome and Principe': 'STP',
	'Saudi Arabia': 'SAU',
	'Senegal': 'SEN',
	'Serbia': 'SRB',
	'Seychelles': 'SYC',
	'Sierra Leone': 'SLE',
	'Singapore': 'SGP',
	'Slovakia': 'SVK',
	'Slovenia': 'SVN',
	'Solomon Islands': 'SLB',
	'Somalia': 'SOM',
	'South Africa': 'ZAF',
	'South Georgia and the South Sandwich Islands': 'SGS',
	'South Sudan': 'SSD',
	'Spain': 'ESP',
	'Sri Lanka': 'LKA',
	'Sudan': 'SDN',
	'Suriname': 'SUR',
	'Svalbard and Jan Mayen Islands': 'SJM',
	'Swaziland': 'SWZ',
	'Sweden': 'SWE',
	'Switzerland': 'CHE',
	'Syrian Arab Republic': 'SYR',
	'Taiwan': 'TWN',
	'Tajikistan': 'TJK',
	'Tanzania': 'TZA',
	'Thailand': 'THA',
	'Timor-Leste': 'TLS',
	'Togo': 'TGO',
	'Tokelau': 'TKL',
	'Tonga': 'TON',
	'Trinidad and Tobago': 'TTO',
	'Tunisia': 'TUN',
	'Turkey': 'TUR',
	'Turkmenistan': 'TKM',
	'Turks and Caicos Islands': 'TCA',
	'Tuvalu': 'TUV',
	'Uganda': 'UGA',
	'Ukraine': 'UKR',
	'United Arab Emirates': 'ARE',
	'United Kingdom': 'GBR',
	'United States of America': 'USA',
	'US Minor Outlying Islands': 'UMI',
	'Uruguay': 'URY',
	'Uzbekistan': 'UZB',
	'Vanuatu': 'VUT',
	'Venezuela': 'VEN',
	'Viet Nam': 'VNM',
	'Virgin Islands': 'VIR',
	'Wallis and Futuna Islands': 'WLF',
	'Western Sahara': 'ESH',
	'Yemen': 'YEM',
	'Zambia': 'ZMB',
	'Zimbabwe': 'ZWE',
	'Aston Villa': 'AVA',
	'Arsenal': 'ARS',
	'Bournemouth': 'BOU',
	'Brentford': 'BRE',
	'Brighton': 'BRH',
	'Chelsea': 'CHE',
	'Crystal Palace': 'CRY',
	'Everton': 'EVE',
	'Fulham': 'FUL',
	'Leeds': 'LEE',
	'Leicester': 'MCI',
	'Manchester City': 'MCI',
	'Manchester United': 'MUN',
	'Liverpool': 'LIV',
	'Newcastle': 'NEW',
	'Nottingham Forest': 'NTG',
	'Southampton': 'SOU',
	'Tottenham': 'TOT',
	'West Ham': 'WHU',
	'Wolves': 'WLV',
	'Reading': 'RED',
	'Wrexham': 'WEX',
	'Derby': 'DRB',
	'Sheffield Utd': 'SHU',
	'Real Madrid': 'RMD',
	'Paris Saint Germain': 'PSG',
	'Bayern Munich': 'BYM',
	'Western United': 'WTU',
	'Adelaide United': 'ADU',
	'Brisbane Roar': 'BBR',
	'Central Coast Mariners': 'CCM',
	'Atlanta Hawks': 'ATL',
	'Brooklyn Nets': 'BKN',
	'Boston Celtics': 'BOS',
	'Charlotte Hornets': 'CHA',
	'Chicago Bulls': 'CHI',
	'Cleveland Cavaliers': 'CLE',
	'Dallas Mavericks': 'DAL',
	'Denver Nuggets': 'DEN',
	'Detroit Pistons': 'DET',
	'Golden State Warriors': 'GSW',
	'Houston Rockets': 'HOU',
	'Indiana Pacers': 'IND',
	'Los Angeles Clippers': 'LAC',
	'Los Angeles Lakers': 'LAL',
	'Memphis Grizzlies': 'MEM',
	'Miami Heat': 'MIA',
	'Milwaukee Bucks': 'MIL',
	'Minnesota Timberwolves': 'MIN',
	'New Orleans Pelicans': 'NOP',
	'New York Pelicans': 'NOP',
	'New York Knicks': 'NYK',
	'Oklahoma City Thunder': 'OKC',
	'Orlando Magic': 'ORL',
	'Philadelphia 76ers': 'PHI',
	'Phoenix Suns': 'PHX',
	'Portland Trail Blazers': 'POR',
	'Sacramento Kings': 'SAC',
	'San Antonio Spurs': 'SAS',
	'Toronto Raptors': 'TOR',
	'Utah Jazz': 'UTA',
	'Washington Wizards': 'WAS',
	'ASPAC': 'ASP',
	'Damissa': 'DAM',
	"Coritiba": "COT",
	"Sport Recife": "SPR",
	"Feyenoord": "FEY",
	"AS Roma": "ROM",
	"Paulistano": "PAU",
	"Brasilia": "BRA",
	"Gimnasia L.P.": "GLP",
	"MZT Skopje":"MZT",
	"Cibona": "CIB",
	"Warta Poznań": "WAP",
	"Slask Wroclaw": "SLW",
	"Inter": "INT",
	"Benfica": "BEN",
	"Napoli": "NAP",
	"AC Milan": "ACM",
	"Arsenal Sarandi": "ASFC",
	"Boca Juniors": "CABJ",
	"River Plate": "CARP",
	"Defensa Y Justicia": "DYJ",
	"New York City FC":"NYC",
	"Columbus Crew":"COC",
	"Orlando City SC":"OSC",
	"Philadelphia Union":"PHU",
	"Colorado Rapids": "COR",
	"Vancouver Whitecaps": "VFC",
	"Los Angeles Galaxy": "LAG",
	"Sporting Kansas City": "SKC",
	"Los Angeles FC": "LAFC",
	"Seattle Sounders": "SFC",
	"Portland Timbers": "POT",
	"Chicago Fire": "CHF",
	"Montreal Impact":"MIC",
	"Austin":"AFC",
	"Inter Miami":"ITM",
	"New York Red Bulls":"NYB",
	"New England Revolution":"NER",
	"FC Cincinnati":"FCC",
	"Houston Dynamo": "DFC",
	"Nashville SC": "NSC",
	"San Jose Earthquakes":"SJE",
	"St. Louis City":"SLC",
	"FC Dallas":"FCD",
	"Real Salt Lake":"RSL",
	"Burnley":"BUR",
	"Luton":"LUT",
	"Arizona Cardinals": "ARZ",
	"Atlanta Falcons":"ATL",
	"Baltimore Ravens":"BLT",
	"Buffalo Bills":"BUF",
	"Carolina Panthers":"CAR",
	"Chicago Bears":"CHI",
	"Cincinnati Bengals":"CIN",
	"Cleveland Browns":"CLV",
	"Dallas Cowboys":"DAL",
	"Denver Broncos":"DEN",
	"Detroit Lions":"DET",
	"Green Bay Packers":"GB",
	"Houston Texans":"HST",
	"Indianapolis Colts":"IND",
	"Jacksonville Jaguars":"JAX",
	"Kansas City Chiefs":"KC",
	"Las Vegas Raiders":"LV",
	"Los Angeles Chargers":"LAC",
	"Los Angeles Rams":"LA",
	"Miami Dolphins":"MIA",
	"Minnesota Vikings":"MIN",
	"New England Patriots":"NE",
	"New Orleans Saints":"NO",
	"New York Giants":"NYG",
	"New York Jets":"NYJ",
	"Philadelphia Eagles":"PHI",
	"Pittsburgh Steelers":"PIT",
	"San Francisco 49ers":"SF",
	"Seattle Seahawks":"SEA",
	"Tampa Bay Buccaneers":"TB",
	"Tennessee Titans":"TEN",
	"Washington Commanders":"WAS"
};
